version: '3.7'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  app:
    build:
      context: .
      dockerfile: compose/local/app/Dockerfile
      args:
        requirements: requirements/local.txt
    command: /start
    env_file:
      - .envs/.local/.app
      - .envs/.local/.postgres
    ports:
      - 80:80
      - 8888:8888
    volumes:
    - ./app:/app

  db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: habr_db
    env_file:
      - .envs/.local/.postgres
    volumes:
      - local_postgres_data_backups:/backups
      - local_postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=768MB"
      - "-c"
      - "effective_cache_size=2304MB"
      - "-c"
      - "maintenance_work_mem=192MB"
      - "-c"
      - "checkpoint_completion_target=0.7"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=3932kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"
      - "-c"
      - "max_parallel_maintenance_workers=2"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: bdabylovb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rootforall
      PGADMIN_LISTEN_PORT: '5050'
    ports:
    - 5050:5050
