"""Create User model, link with Post, make field nullable

Revision ID: beaa35fab64b
Revises: 72191aee2d1b
Create Date: 2020-03-06 10:34:09.152594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beaa35fab64b'
down_revision = '72191aee2d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
